# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20190509_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ManyToManyField(to='insta.Location'),
        ),
    ]
